branch-defaults:
  main:
    environment: null
    group_suffix: null
  master:
    environment: project-dosimage-env
    group_suffix: null
global:
  application_name: project-dosimage
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.6
  default_region: sa-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
